<?php
session_start();
require_once 'config.php'; // Include the config file to initialize $conn

if (!isset($_GET['event_id'])) {
    die("No event selected.");
}

$event_id = intval($_GET['event_id']);

// Check if username is set in the session
if (!isset($_SESSION['username'])) {
    die("User not logged in or session expired.");
}

$username = $_SESSION['username']; // Assuming username is stored in session

// Function to generate a unique report ID
function generateReportId($conn) {
    $result = $conn->query("SELECT MAX(report_id) AS max_id FROM report");
    $row = $result->fetch_assoc();
    return ($row['max_id'] ?? 0) + 1;
}

// Fetch the admin's full name from the users table
$sql = "SELECT full_name FROM users WHERE username = ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param('s', $username);
$stmt->execute();
$result = $stmt->get_result();

$full_name = 'Admin'; // Default value if user is not found
if ($result->num_rows > 0) {
    $user = $result->fetch_assoc();
    $full_name = $user['full_name'];
}

// Generate the value for $generated_by
$generated_by = $full_name;

// Generate the report ID, date, and generated by
$report_id = generateReportId($conn);
$generated_on = date('Y-m-d H:i:s');

// Fetch event name for the selected event
$event_sql = "SELECT event_name FROM events WHERE event_id = ?";
$stmt = $conn->prepare($event_sql);
$stmt->bind_param("i", $event_id);
$stmt->execute();
$event_result = $stmt->get_result();

$event_name = 'Unknown Event'; // Default value if event is not found
if ($event_result->num_rows > 0) {
    $event = $event_result->fetch_assoc();
    $event_name = $event['event_name'];
}

// Fetch payment data for the selected event
$sql = "
    SELECT 
        p.payment_id, 
        u.full_name AS customer_name, 
        u.gender AS customer_gender, 
        p.purchase_id,
        t.ticket_number, 
        t.seat_number,  
        t.ticket_price_ksh, 
        p.payment_date, 
        p.payment_method, 
        p.status,
        b.number_of_tickets, 
        b.total_amount_ksh
    FROM 
        payments p
    JOIN 
        users u ON p.user_id = u.user_id
    JOIN
        purchases b ON p.purchase_id = b.purchase_id
    JOIN 
        tickets t ON t.purchase_id = b.purchase_id
    WHERE 
        b.event_id = ?
";
$stmt = $conn->prepare($sql);
$stmt->bind_param("i", $event_id);
$stmt->execute();
$result = $stmt->get_result();

$payments = [];
$total_amount = 0;
$total_tickets = 0;
$people_per_gender = ['Male' => 0, 'Female' => 0, 'Other' => 0]; // Adjust based on gender options

if ($result) {
    while ($row = $result->fetch_assoc()) {
        $payments[] = $row;
        $total_amount += $row['total_amount_ksh'];
        $total_tickets += $row['number_of_tickets'];
        $people_per_gender[$row['customer_gender']] += $row['number_of_tickets'];
    }
}

// Insert the report details into the report table for the selected event
$insert_sql = "INSERT INTO report (report_id, generated_on, generated_by) VALUES (?, ?, ?)";
$stmt = $conn->prepare($insert_sql);
$stmt->bind_param("iss", $report_id, $generated_on, $generated_by);
$stmt->execute();

// Close the database connection
$conn->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
            background-color: #f4f4f4;
            text-align: center;
        }
        h1 {
            color: #0056b3;
            border-bottom: 2px solid #0056b3;
            padding-bottom: 10px;
        }
        p, h2, h3, h4, h5 {
            color: #0056b3;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        hr {
            border: 0;
            border-top: 1px solid #ddd;
            margin: 20px 0;
        }
        button {
            background-color: #0056b3;
            color: #fff;
            border: none;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 10px 0;
            cursor: pointer;
        }
        button:hover {
            background-color: #004494;
        }
    </style>
</head>
<body>

    <h1>Payment Report for: <?php echo htmlspecialchars($event_name); ?></h1>
    <p><strong>Report ID:</strong> <?php echo htmlspecialchars($report_id); ?></p>
    <p><strong>Generated On:</strong> <?php echo htmlspecialchars($generated_on); ?></p>
    <p><strong>Generated By:</strong> <?php echo htmlspecialchars($generated_by); ?></p>
    <hr>

    <h3>Payment Details</h3>
    <table>
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Gender</th>
                <th>Ticket Number</th>
                <th>Ticket Price (Ksh)</th>
                <th>Seat Number</th>
                <th>Payment Date</th>
                <th>Payment Method</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($payments as $payment): ?>
                <tr>
                    <td><?php echo htmlspecialchars($payment['customer_name']); ?></td>
                    <td><?php echo htmlspecialchars($payment['customer_gender']); ?></td>
                    <td><?php echo htmlspecialchars($payment['ticket_number']); ?></td>
                    <td><?php echo htmlspecialchars($payment['ticket_price_ksh']); ?></td>
                    <td><?php echo htmlspecialchars($payment['seat_number']); ?></td>
                    <td><?php echo htmlspecialchars($payment['payment_date']); ?></td>
                    <td><?php echo htmlspecialchars($payment['payment_method']); ?></td>
                    <td><?php echo htmlspecialchars($payment['status']); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <hr>
    <h4>Summary</h4>
    <p><strong>Total Tickets:</strong> <?php echo htmlspecialchars($total_tickets); ?></p>
    <p><strong>Total Amount (Ksh):</strong> <?php echo htmlspecialchars($total_amount); ?></p>
    <ul>
        <?php foreach ($people_per_gender as $gender => $count): ?>
            <li><?php echo htmlspecialchars($gender); ?>: <?php echo htmlspecialchars($count); ?></li>
        <?php endforeach; ?>
    </ul>
    <button onclick="window.print()">Print Report</button>

</body>
</html>